# Notebook for getting nodule_probability_vector for each region in Kaggle-Dataset image

This notebook takes data from Kaggle-data and creates probabilty of nodule presence in each region of the image

In [1]:
import pydicom # for reading dicom files
from scipy import ndimage as nd
import os # for doing directory operations 
import pandas as pd # for some simple data analysis (right now, just to load in the labels data and quickly reference it)
import numpy as np
import sklearn

data_dir = 'D:\\riya\\DL-MP\\kaggle\\stage1\\stage1\\'
patients = os.listdir(data_dir)
labels_df = pd.read_csv('D:\\riya\\DL-MP\\kaggle\\stage1_labels\\stage1_labels.csv', index_col=0)
print(len(patients))
labels_df.head(50)

1397


cancer
id                                      
0015ceb851d7251b8f399e39779d1e7d       1
0030a160d58723ff36d73f41b170ec21       0
003f41c78e6acfa92430a057ac0b306e       0
006b96310a37b36cccb2ab48d10b49a3       1
008464bb8521d09a42985dd8add3d0d2       1
0092c13f9e00a3717fdc940641f00015       0
00986bebc45e12038ef0ce3e9962b51a       0
00cba091fa4ad62cc3200a657aeb957e       0
00edff4f51a893d80dae2d42a7f45ad1       1
0121c2845f2b7df060945b072b2515d7       0
013395589c01aa01f8df81d80fb0e2b8       0
01de8323fa065a8963533c4a86f2f6c1       0
01e349d34c06410e1da273add27be25c       0
01f1140c8e951e2a921b61c9a7e782c2       0
024efb7a1e67dc820eb61cbdaa090166       0
0257df465d9e4150adef13303433ff1e       1
0268f3a7a17412178cfb039e71799a80       0
026be5d5e652b6a7488669d884ebe297       0
02801e3bbcc6966cb115a962012c35df       1
028996723faa7840bb57f57e28275e4c       1
0334c8242ce7ee1a6c1263096e4cc535       0
03fb0d0fdb187ee1160f09386b28c3f2       0
03ff23e445787886f8b0cb192b3c154d       0
043ed6cb6054cc13804a3dca342fa4d0       0
0482c444ac838adc5aa00d1064c976c1       0
04a3187ec2ed4198a25033071897bffc       0
04a52f49cdbfb8b99789b9e93f1ad319       0
04a8c47583142181728056310759dea1       1
04cfc5efa4c8c2a8944c8b9fa6cb04d1       0
04e5d435fa01b0958e3274be73312cac       0
04fca9fbec0b803326488ade96897f6e       0
05609fdb8fa0895ac8a9be373144dac7       1
059d8c14b2256a2ba4e38ac511700203       1
05a20caf6ab6df4643644c953f06a5eb       0
064366faa1a83fdcb18b2538f1717290       1
0679e5fd67b7441b8094494033f3881f       0
0700108170c91ea2219006e9484999ef       0
0708c00f6117ed977bbe1b462b56848c       1
07349deeea878c723317a1ce42cc7e58       1
07abb7bec548d1c0ccef088ce934e517       0
07bca4290a2530091ce1d5f200d9d526       1
07fdb853ff90ce3c6d5c91f619ed714e       0
080e6a00e69888fd620894f9fd0714b1       0
081f4a90f24ac33c14b61b97969b7f81       1
08528b8817429d12b7ce2bf444d264f9       0
0852f5124d69d7f8cd35fa31e1364d29       0
08643d7b9ce18405fb63f63dda258e76       0
086f95a932c83faed289854083f48831       0
0890a698c0a6ce5db48b1467011bf8d2       0
089b8f10743e449a0f64f8f311dd8a46       0

In [2]:
def crop_center(img,cropx,cropy):
    y,x = img.shape
    startx = x//2-(cropx//2)
    starty = y//2-(cropy//2)    
    return img[starty:starty+cropy,startx:startx+cropx]


In [ ]:
import matplotlib.pyplot as plt
from keras.models import load_model
import cv2

for patient in patients:
    print(patient)
    #label = labels_df.get_value(patient, 'cancer')
    label = labels_df.at[patient, 'cancer']
    path = data_dir + patient
    
    slices = [pydicom.read_file(path + '/' + s) for s in os.listdir(path)]
    #cv2.imshow('image',slices[0])
    num = len(slices)/36
    num_int = int(num)
    last_slice = 36*num_int
    
    #print(slices)
    #slices = np.array(slices[:last_slice])
    
    temp_arr = [crop_center(slices[i].pixel_array, 504, 504) for i in range(len(slices))]
    temp_arr = np.array(temp_arr)
    print(temp_arr.shape)
    zoomFactors = [504/float(a) for a in temp_arr.shape]

    temp_arr = nd.interpolation.zoom(temp_arr, zoom=zoomFactors) 
    print(temp_arr.shape)
    new_arr =  np.split(temp_arr, 14)
    
    
    
    all_splits = []
    
    model = load_model('C:\\Users\\dc\\Documents\\riya\\Lung-Cancer-Detection-master\\Output\\model.h5')

    all_elems = []
    for item in new_arr:

        
        nd_arr = np.split(item,14,1)
        nd_arr = np.array(nd_arr)
        
        for it in nd_arr:
            
            nd_new = np.split(it,14, 2)
            nd_new = np.array(nd_new)
            for elem in nd_new:
                
                elem = elem.reshape(1,36,36,36)
                all_elems.append(elem)
    all_elems = np.array(all_elems)
    new_tuple = model.predict_proba(all_elems, batch_size = 32)
    print(type(new_tuple[0][1]))
    print(new_tuple)
    print(len(new_tuple))


Using TensorFlow backend.


0015ceb851d7251b8f399e39779d1e7d
(195, 504, 504)
(504, 504, 504)
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
0030a160d58723ff36d73f41b170ec21
(265, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
003f41c78e6acfa92430a057ac0b306e
(233, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0.47609058 0.5239094 ]
 [0.         1.        ]
 [0.         1.        ]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.05807708 0.9419229 ]]
2744
006b96310a37b36cccb2ab48d10b49a3
(173, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 ...
 [0.47609058 0.5239094 ]
 [0.47609058 

C:\Users\dc\Anaconda3\envs\mrudang\lib\site-packages\scipy\ndimage\interpolation.py:605: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)


(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
01e349d34c06410e1da273add27be25c
(159, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[1.1261095e-26 1.0000000e+00]
 [5.3687363e-28 1.0000000e+00]
 [6.8849777e-27 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744
01f1140c8e951e2a921b61c9a7e782c2
(241, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
024efb7a1e67dc820eb61cbdaa090166
(175, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[4.7609058e-01 5.2390939e-01]
 [4.7609058e-01 5.2390939e-01]
 [2.1533521e-36 1.0000000e+00]
 ...
 [4.7609058e-01 5.2390939e-01]
 [4.7609058e-01 5.2390939e-01]
 [4.7609058e-01 5.2390939e-01]]
2744
0257df465d9e4150adef13303433ff1e
(186, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
0268f3a7a174121

(175, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
09fdf599084b816247ba38d95b3c9d80
(120, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
0a099f2549429d29b32f349e95fb2244
(128, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
0a0c32c9e08cc2ea76a71649de56be6d
(133, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 ...
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]]
2744
0a38e7597ca26f9374f8ea2770ba870d
(110, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
0acbebb8d463b4b9ca88cf38431aac69
(203, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[9.257331e-27 1.000000e+00]
 [4.808481e-30 1.000000e+00]
 [6.650801e-30 1.000

(169, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[1.7577752e-37 1.0000000e+00]
 [6.5654207e-38 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744
12e0e2036f61c8a52ee4471bf813c36a
(134, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
1344e604281e68ac71f25c02e7637992
(352, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
135f21a84ac903a1d8dfbb0dfe46d792
(243, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
13bb12b3b27d5a7b4b142503a1ae9e73
(172, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[8.2770292e-36 1.0000000e+00]
 [2.2896172e-37 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744

(139, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
1acbe17dc8f9f59d2fd167b2aa6c650f
(179, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[4.2600460e-37 1.0000000e+00]
 [3.0636813e-38 1.0000000e+00]
 [5.7315316e-38 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744
1b17c83c3b0cb973e41f9121e562d030
(162, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[6.1140425e-05 9.9993885e-01]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744
1b2355e6054759f2f0eb2542ed382b78
(155, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
1b7ca8dad5c36feb0a6abf8079173e22
(298, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744

(215, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
252b5fd5c4a5eb77be4fbe41df49bd07
(324, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[7.6662479e-37 1.0000000e+00]
 [3.1958792e-36 1.0000000e+00]
 [1.5300572e-36 1.0000000e+00]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
2744
25782c40c29f7d774f8b644f3e68b590
(197, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
25a3b616f6cc89e74f6502d65b687972
(173, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 ...
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]
 [0.47609058 0.5239094 ]]
2744
25c1c4f008e8addc4d386cab58815052
(116, 504, 504)
(504, 504, 504)
<class 'numpy.float32'>
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
2744
25c369973827571098bdebf2a15c6ef2
(1